'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

type Profile = { id:string; name:string; provider_type:string; public_ip:string|null; status:string };

export default function Network(){
  const [profiles,setProfiles]=useState<Profile[]>([]); const [teamId,setTeamId]=useState<string|null>(null); const [role,setRole]=useState(''); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [type,setType]=useState('egress'); const [ip,setIp]=useState(''); const [notice,setNotice]=useState('');
  const flash=(x:string)=>{setNotice(x);window.setTimeout(()=>setNotice(''),2500)};
  const load=async()=>{if(!supabase)return; const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href='/login';return;} const {data:m}=await supabase.from('team_members').select('team_id,role').eq('user_id',user.id).limit(1).maybeSingle(); if(!m){setLoading(false);return;} setTeamId(m.team_id);setRole(m.role);const {data}=await supabase.from('network_profiles').select('id,name,provider_type,public_ip,status').eq('team_id',m.team_id).order('created_at',{ascending:true});setProfiles((data??[]) as Profile[]);setLoading(false)};
  useEffect(()=>{load()},[]);
  const add=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!teamId||!name.trim())return;const {data,error}=await supabase.from('network_profiles').insert({team_id:teamId,name:name.trim(),provider_type:type,public_ip:ip.trim()||null,status:ip.trim()?'Configured':'Offline'}).select('id,name,provider_type,public_ip,status').single();if(error){flash(`Profil konnte nicht gespeichert werden: ${error.message}`);return;}if(data)setProfiles(p=>[...p,data as Profile]);setOpen(false);setName('');setIp('');setType('egress');flash('Netzwerkprofil gespeichert');};
  const remove=async(id:string)=>{if(!supabase)return;const {error}=await supabase.from('network_profiles').delete().eq('id',id);if(error){flash(`Profil konnte nicht gelöscht werden: ${error.message}`);return;}setProfiles(p=>p.filter(x=>x.id!==id));flash('Profil gelöscht');};
  if(loading)return <main className="main"><div className="eyebrow">Infrastruktur</div><h1 className="title">Netzwerk</h1><div className="card"><p className="muted">Netzwerkprofile werden geladen…</p></div></main>;
  const canManage=role==='Owner'||role==='Admin';
  return <main className="main"><div className="eyebrow">Infrastruktur</div><h1 className="title">Netzwerk</h1><p className="muted">Account → Network Profile → Egress. Die Zuordnung bleibt unabhängig vom verwendeten Gerät.</p>{notice&&<div className="toast">✓ {notice}</div>}
    <section className="card section"><div className="sectionhead"><div><h2>Network Profiles</h2><div className="muted">{profiles.length} Profil{profiles.length===1?'':'e'}</div></div>{canManage&&<button className="button" onClick={()=>setOpen(true)}>+ Profil</button>}</div>
      {profiles.length===0?<div className="empty"><strong>Noch kein Netzwerkprofil</strong><div className="muted">Lege ein Profil an, bevor ein Spielaccount einer festen Egress-Verbindung zugeordnet wird.</div></div>:<div className="table-wrap"><table className="table"><thead><tr><th>Profil</th><th>Typ</th><th>Öffentliche IP</th><th>Status</th><th></th></tr></thead><tbody>{profiles.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.provider_type}</td><td>{p.public_ip||'—'}</td><td><span className={'pill '+(p.status==='Configured'?'online':'')}>{p.status}</span></td><td>{canManage&&<button className="button secondary" onClick={()=>remove(p.id)}>Löschen</button>}</td></tr>)}</tbody></table></div>}
    </section>
    <section className="card section"><h2>Feste IP – Architektur</h2><p className="muted">Ein Profil beschreibt die gewünschte Egress-Verbindung. Die eigentliche feste öffentliche IP entsteht erst auf einer serverseitigen Egress-/Proxy-Schicht; die WebApp selbst ändert nicht die IP deines iPhones oder PCs.</p><p className="muted">Wichtig: Eine eigene IP pro Spielaccount ist technisch möglich, benötigt aber einen dauerhaft erreichbaren Egress-Server bzw. Proxy pro IP. Für die spätere Umsetzung halten wir die Zuordnung hier bereits accountbezogen.</p></section>
    {open&&<div className="modalBackdrop" onMouseDown={()=>setOpen(false)}><div className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><div className="eyebrow">Teamzentrale Odin</div><h2>Netzwerkprofil</h2></div><button className="iconButton" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={add}><label className="field">Profilname<input value={name} onChange={e=>setName(e.target.value)} placeholder="z. B. Odin-Account-01" required/></label><label className="field">Typ<select value={type} onChange={e=>setType(e.target.value)}><option value="egress">Egress</option><option value="proxy">Proxy</option><option value="vpn">VPN</option></select></label><label className="field">Öffentliche IP <span className="muted">optional</span><input value={ip} onChange={e=>setIp(e.target.value)} placeholder="z. B. 203.0.113.10" inputMode="decimal"/></label><div className="modalActions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Abbrechen</button><button className="button">Profil speichern</button></div></form></div></div>}
  </main>;
}
